/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pl_incrementalupdata_Bspatch */

#ifndef _Included_com_pl_incrementalupdata_Bspatch
#define _Included_com_pl_incrementalupdata_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pl_incrementalupdata_Bspatch
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pl_incrementalupdata_Bspatch_bsPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
